### ISSUE TITLE
Gradle Dependency

### ISSUE THREAD

**Issue by u2gilles** [rahulrj/Swipe_RecyclerView#2]
I am trying to use the lib only in Studio. What dependency should i use in file build.gradle?
The dependency of SwipeListView is :
dependencies {
    compile ('com.fortysevendeg.swipelistview:swipelistview:1.0-SNAPSHOT@aar') {
        transitive = true
    }
}
But what is the dependency of Swipe_RecyclerView ? I can't find it on your sites.

PS : Is transitive = true necessary?

**Comment by rahulrj** [comment]
@u2gilles , using the dependency, we can reference the library from a central 'server' like maven central. But currently this facility is not available for this library. So you will have to include it with the project. But i will host it shortly.

**Comment by u2gilles** [comment]
Thanks.  I will use the .AAR file for the moment.

**Comment by emce** [comment]
Can you give any ETA?
